ual_bucket: "ual-minute-calibration"
ual_sensor: "ual-5"
lubw_bucket: "lubw-hour"
lubw_sensor: "DEBW015"
start_time: "2025-09-08T00:00:00Z"
stop_time: "2025-10-02T00:00:00Z"
inputs:
  - RAW_ADC_NO2_W
  - RAW_ADC_NO2_A
  - RAW_ADC_NO_W
  - RAW_ADC_NO_A
  - RAW_ADC_O3_W
  - RAW_ADC_O3_A
  - sht_temp
  - sht_humid
targets:
  - O3
experiment_name: "Random Forest Models"
run_name: "O3-ual5-1"