ual_bucket: "ual-minute-calibration"
ual_sensor: "ual-3"
lubw_bucket: "lubw-hour"
lubw_sensor: "DEBW015"
start_time: "2024-11-16T00:00:00Z"
stop_time: "2025-03-08T20:00:00Z"
inputs:
  - RAW_ADC_NO_W
  - RAW_ADC_NO_A
targets:
  - "NO"
experiment_name: "Residuals"
run_name: "Residuals1"