name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install uv
      run: |
        python -m pip install --upgrade pip
        pip install uv

    - name: Install dependencies with uv
      run: |
        uv sync --locked

    - name: Run tests with pytest
      run: |
        uv run pytest

    - name: Run linter with ruff
      run: uv run ruff check .

    - name: Run security check with pip-audit
      continue-on-error: true
      run: uv run pip-audit
